# --- !Ups
CREATE TABLE HQ_USER (
  USER_ID    VARCHAR(50) PRIMARY KEY,
  NICKNAME   VARCHAR(100) NOT NULL,
  EMAIL      VARCHAR(100) NOT NULL,
  AVATAR_URL VARCHAR(200) NULL,
  ACTIVATED  BOOLEAN      NOT NULL
);
CREATE TABLE AUTH_TOKEN (
  ID      VARCHAR(50) PRIMARY KEY,
  USER_ID VARCHAR(50) NOT NULL REFERENCES HQ_USER (USER_ID),
  EXPIRY  TIMESTAMP   NOT NULL
);

CREATE TABLE LOGIN_INFO (
  ID           BIGSERIAL PRIMARY KEY,
  PROVIDER_ID  VARCHAR NOT NULL,
  PROVIDER_KEY VARCHAR NOT NULL
);

CREATE TABLE USER_LOGIN_INFO (
  USER_ID       VARCHAR(50) NOT NULL REFERENCES HQ_USER (USER_ID),
  LOGIN_INFO_ID BIGINT      NOT NULL REFERENCES LOGIN_INFO (ID)
);

CREATE TABLE HQ_SUPERUSER (
  ID      SERIAL PRIMARY KEY,
  USER_ID VARCHAR(50) UNIQUE NOT NULL REFERENCES HQ_USER (USER_ID)
);

CREATE TABLE HQ_ADMIN (
  ID      SERIAL PRIMARY KEY,
  USER_ID VARCHAR(50) UNIQUE NOT NULL REFERENCES HQ_USER (USER_ID)
);

CREATE TABLE HQ_GAME_ADMIN (
  ID      SERIAL PRIMARY KEY,
  GAME_ID INT         NOT NULL,
  USER_ID VARCHAR(50) NOT NULL REFERENCES HQ_USER (USER_ID),
  UNIQUE (GAME_ID, USER_ID)
);

CREATE TABLE OAUTH1_INFO (
  ID            BIGSERIAL PRIMARY KEY,
  TOKEN         VARCHAR NOT NULL,
  SECRET        VARCHAR NOT NULL,
  LOGIN_INFO_ID BIGINT  NOT NULL REFERENCES LOGIN_INFO (ID)
);

CREATE TABLE OAUTH2_INFO (
  ID            BIGSERIAL PRIMARY KEY,
  ACCESS_TOKEN  VARCHAR NOT NULL,
  TOKEN_TYPE    VARCHAR NULL,
  EXPIRES_IN    INT     NULL,
  REFRESH_TOKEN VARCHAR NULL,
  LOGIN_INFO_ID BIGINT  NOT NULL REFERENCES LOGIN_INFO (ID)
);

CREATE TABLE OPENID_INFO (
  ID            VARCHAR PRIMARY KEY,
  LOGIN_INFO_ID BIGINT NOT NULL REFERENCES LOGIN_INFO (ID)
);

CREATE TABLE OPENID_ATTRIBUTES (
  ID    VARCHAR NOT NULL,
  KEY   VARCHAR NOT NULL,
  VALUE VARCHAR NOT NULL
);

CREATE TABLE PASSWORD_INFO (
  HASHER        VARCHAR NOT NULL,
  PASSWORD      VARCHAR NOT NULL,
  SALT          VARCHAR NULL,
  LOGIN_INFO_ID BIGINT  NOT NULL REFERENCES LOGIN_INFO (ID),
  PRIMARY KEY (LOGIN_INFO_ID)
);

# --- !Downs
DROP TABLE OPENID_ATTRIBUTES;
DROP TABLE OPENID_INFO;
DROP TABLE OAUTH2_INFO;
DROP TABLE OAUTH1_INFO;
DROP TABLE PASSWORD_INFO;
DROP TABLE USER_LOGIN_INFO;
DROP TABLE LOGIN_INFO;
DROP TABLE HQ_SUPERUSER;
DROP TABLE HQ_ADMIN;
DROP TABLE HQ_GAME_ADMIN;
DROP TABLE HQ_USER;































